name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build

      - name: Deploy to GitHub Pages (v2)
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages  # Or any other branch you'd like to deploy to
          folder: dist  # Replace <your-project-name> with your actual project name
          token: ${{ secrets.GITHUB_TOKEN }}
